config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 장고에서는 from . import settings가 아님

# 이유 : config.settings.py에서 작성한 것이 반영된것을 import 하는 것이기 떄문에
from django.conf.urls.static import static  # path를 return 해주는 도우미역할
from rooms import views as room_views

urlpatterns = [  # path(usl , views)
    path("", include("core.urls", namespace="core")),
    path(
        "rooms/", include("rooms.urls", namespace="rooms")
    ),  # room_list.html의 url 태그에 쓰일 namespace room:detail
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # 개발자모드일때만 되길 원해
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# 아무것도 없는 url을 core에 정의 할 것이다.
from django.urls import path
from rooms import views as room_views

# 필수
app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
]

templates/partials/footer.html
<footer>
    &copy; Nbnb
</footer>

templates/partials/nav.html
<a href={% url "core:home" %}>Nbnb</a>
<ul>
    {% if user.is_authenticated %}
    <li>
        <a href="{% url 'users:logout'%}">Log out {{user.username}}</a>
    </li>
    {% else %}
    <li>
        <a href="{% url 'users:login'%}">Log in</a>
        <a href="{% url 'users:signup'%}">Sign Up</a>
    </li>
    {% endif %}

</ul>