config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 장고에서는 from . import settings가 아님

# 이유 : config.settings.py에서 작성한 것이 반영된것을 import 하는 것이기 떄문에
from django.conf.urls.static import static  # path를 return 해주는 도우미역할
from rooms import views as room_views

urlpatterns = [  # path(usl , views)
    path("", include("core.urls", namespace="core")),
    path(
        "rooms/", include("rooms.urls", namespace="rooms")
    ),  # room_list.html의 url 태그에 쓰일 namespace room:detail
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:  # 개발자모드일때만 되길 원해
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
# 아무것도 없는 url을 core에 정의 할 것이다.
from django.urls import path
from rooms import views as room_views

# 필수
app_name = "core"

urlpatterns = [
    path("", room_views.HomeView.as_view(), name="home"),
]

rooms/urls.py
from django.urls import path
from . import views


app_name = "rooms"

urlpatterns = [
    path(
        "<int:pk>",
        views.RoomDetail.as_view(),
        name="detail",
    ),  # room_list.html의 url 태그에 쓰일 namespace room:detail
    path("search/", views.SearchView.as_view(), name="search"),
]

rooms/models.py
# 파이썬
from django.db import models  # 쟝고
from django.urls import reverse  # url name이 필요, retrun url
from django_countries.fields import CountryField  # 써드파티
from core import models as core_models  # 사용자패키지
from users import models as user_models

# 룸의 여러 설정들
class AbstractItem(core_models.TimeStampedModel):

    """Abstract Item"""

    name = models.CharField(max_length=80)

    class Meta:
        abstract = True

    def __str__(self):
        return self.name


class RoomType(AbstractItem):

    """RoomType Model Definition"""

    class Meta:
        verbose_name = "RoomType"
        ordering = ["created"]

    pass


class Amenity(AbstractItem):
    """Amenity Model Definition"""

    class Meta:
        verbose_name_plural = "Amenities"

    pass


class Facility(AbstractItem):
    """Facility Model Definition"""

    class Meta:
        verbose_name_plural = "Facilities"

    pass


class Rule(AbstractItem):
    """ HouseRule Model Definition"""

    class Meta:
        verbose_name = "House Rule"

    pass


# 사진
class Photo(core_models.TimeStampedModel):
    """Photo Model Definition"""

    caption = models.CharField(max_length=80)
    file = models.ImageField(upload_to="room_photos")
    room = models.ForeignKey(
        "Room", related_name="photos", on_delete=models.CASCADE
    )  # Room은 밑에있기 떄문에 인식x -> string으로 바꿔줘서 패스시킬수 있다.

    def __str__(self):
        return self.caption


# 기본 룸 정보
class Room(core_models.TimeStampedModel):

    """Rooom Model Definition"""

    name = models.CharField(max_length=140)
    description = models.TextField()
    country = CountryField()
    city = models.CharField(max_length=80)
    price = models.IntegerField()
    address = models.CharField(max_length=140)
    guests = models.IntegerField(null=True)
    beds = models.IntegerField()
    bathrooms = models.IntegerField()
    bedrooms = models.IntegerField()
    check_in = models.TimeField()
    check_out = models.TimeField()
    istant_book = models.BooleanField(default=False)
    host = models.ForeignKey(
        "users.User",
        on_delete=models.CASCADE,
        related_name="rooms",  # user_model.User -> "users.User"
    )  # 1대 다 관계는 포링키필드 //유저삭제시 룸도삭제//on_delete는 포링키에만
    # related_name은 user가 어떻게 우릴찾기 원합니까
    room_type = models.ForeignKey(
        "RoomType",
        on_delete=models.SET_NULL,
        related_name="rooms",
        null=True,
        blank=True,
    )  # 다대다 관계는 매니투매니필드
    amenity = models.ManyToManyField("Amenity", related_name="rooms", blank=True)
    facility = models.ManyToManyField("Facility", related_name="rooms", blank=True)
    rule = models.ManyToManyField("Rule", related_name="rooms", blank=True)

    def __str__(self):  # admin패널에 나오는 이름을 name으로 보기 위해//원래는 RoomObject(1)
        return self.name

    def save(self, *args, **kwargs):  # 장고의 save를 오버라이딩
        # self.city = str.capitalize(self.city)  # 앞글자를 대문자로
        self.city = self.city.title()  # 모든 단어 첫글자를 대문자로
        super().save(*args, **kwargs)

    # 오버라이딩 한 것
    # admin에서 view on site 버튼 생성
    def get_absolute_url(self):
        return reverse(
            "rooms:detail", kwargs={"pk": self.pk}
        )  # namespace(config.url.py):name(rooms.url.py)

    # room은 리뷰평균을 가지고 있고 사용자화면에서 보이니까 model에서 정의
    # review 모델에 room이 있기 때문에 room도 리뷰를 가지고 있는 것과 마찬가지다.
    def total_rating(self):
        all_reviews = self.reviews.all()  # related name이 reviews이기 때문에
        all_ratings = 0
        if len(all_reviews) > 0:
            for review in all_reviews:
                all_ratings += review.rating_average()
            return round(all_ratings / len(all_reviews), 2)

rooms/forms.py
from django import forms
from . import models
from django_countries.fields import CountryField


class SearchForm(forms.Form):

    city = forms.CharField(required=False)  # ,initial="Anywhere")
    country = CountryField(default="KR").formfield()
    room_type = forms.ModelChoiceField(
        required=False, empty_label="Any Kind", queryset=models.RoomType.objects.all()
    )
    price = forms.IntegerField(required=False)
    guests = forms.IntegerField(required=False)
    bedrooms = forms.IntegerField(required=False)
    beds = forms.IntegerField(required=False)
    baths = forms.IntegerField(required=False)
    instant_book = forms.BooleanField(required=False)
    superhost = forms.BooleanField(required=False)
    amenities = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Amenity.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
    )
    facilites = forms.ModelMultipleChoiceField(
        required=False,
        queryset=models.Facility.objects.all(),
        widget=forms.CheckboxSelectMultiple(),
    )

rooms/views.py
from django.views.generic import ListView, DetailView, View
from django.shortcuts import render
from django.core.paginator import Paginator
from django_countries import countries
from . import models, forms


class HomeView(ListView):
    """ Home View Define"""

    model = models.Room
    paginate_by = 10
    paginate_orphans = 6
    ordering = "created"
    context_object_name = "rooms"  # object_list 대신 rooms



class RoomDetail(DetailView):

    """RoomDetail Definition"""

    model = models.Room
    pk_url_kwarg = "pk"  # pk이름을 바꾸는 것  pk_url_kwarg = "potato" <= urls.py pa th("<int:potato>", views.RoomDetail.as_view(), name="detail")


# 클래스 뷰 기반으로 옮김(def search(requst)->class ss(View):def get(self, requst))
class SearchView(View):
    def get(self, request):
        country = request.GET.get("country")
        if country:
            form = forms.SearchForm(request.GET)
            if form.is_valid():
                city = form.cleaned_data.get("city")
                country = form.cleaned_data.get("country")
                room_type = form.cleaned_data.get("room_type")
                price = form.cleaned_data.get("price")
                guests = form.cleaned_data.get("guests")
                bedrooms = form.cleaned_data.get("bedrooms")
                beds = form.cleaned_data.get("beds")
                baths = form.cleaned_data.get("baths")
                instant_book = form.cleaned_data.get("instant_book")
                superhost = form.cleaned_data.get("superhost")
                amenities = form.cleaned_data.get("amenities")
                facilites = form.cleaned_data.get("facilites")

                filter_args = {}

                # city 필터
                if city != "Antwhere":
                    filter_args["city__startswith"] = city
                # country 필터
                filter_args["country"] = country
                # room_type(foreign key) 필터
                if room_type is not None:
                    filter_args["room_type"] = room_type
                # price
                if price is not None:
                    filter_args["price__lte"] = price

                # guest
                if guests is not None:
                    filter_args["guests__gte"] = guests
                # bedrooms
                if bedrooms is not None:
                    filter_args["bedrooms__gte"] = bedrooms
                # bathrooms
                if baths is not None:
                    filter_args["bathrooms__gte"] = baths
                # beds
                if beds is not None:
                    filter_args["beds__gte"] = beds

                if instant_book is True:
                    filter_args["istant_book"] = True
                if superhost is True:
                    filter_args[
                        "host__superhost"
                    ] = True  # superhost는 foreign key니까 모델안에서 끌고와야함

                for a in amenities:
                    filter_args["amenity"] = a

                for f in facilites:
                    filter_args["facility"] = f

                qs = models.Room.objects.filter(**filter_args).order_by("-created")

                paginator = Paginator(qs, 10, orphans=5)
                page = request.GET.get("page", 1)
                rooms = paginator.get_page(page)

                return render(
                    request, "rooms/search.html", {"form": form, "rooms": rooms}
                )

        else:
            form = forms.SearchForm()

        return render(
            request,
            "rooms/search.html",
            {
                "form": form,
            },
        )

templates/rooms/detail.html
{% extends 'base.html' %}


{% block page_name %}
Home
{% endblock page_name %}


{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>

<div>
    <h2>By : {{room.host.username}}

        {% if room.host.superhost %}
        (superhost)
        {% endif %}

    </h2>
    <h3>
        Amenities
        <ul>{% for a in room.amenity.all %}
            <li>{{a}}</li>
            {% endfor %}
        </ul>
        <ul>
            Facility
            {% for f in room.facility.all %}
            <li>{{f}}</li>
            {% endfor %}
        </ul>
        <ul>House Rules</ul>

        {% for r in room.rule.all %}
        <li></li>
        {% endfor %}


    </h3>
</div>

{%endblock%}

templates/rooms/room_detail.html
{% extends 'base.html' %}


{% block page_title %}
{{room.name}}
{% endblock page_title %}


{% block content %}
<div>
    <h1>{{room.name}}</h1>
    <h3>{{room.description}}</h3>
</div>

<div>
    <h2>By : {{room.host.username}}

        {% if room.host.superhost %}
        (superhost)
        {% endif %}

    </h2>
    <h3>
        Amenities
        <ul>{% for a in room.amenity.all %}
            <li>{{a}}</li>
            {% endfor %}
        </ul>
        <ul>
            Facility
            {% for f in room.facility.all %}
            <li>{{f}}</li>
            {% endfor %}
        </ul>
        <ul>House Rules</ul>

        {% for r in room.rule.all %}
        <li></li>
        {% endfor %}


    </h3>
</div>

{%endblock%}

templates/rooms/room_list.html
{% extends 'base.html' %}


{% block page_title %}
Home
{% endblock page_title %}


{% block content %}

{% for room in rooms %}
<h3>
    <a href="{% url 'rooms:detail' room.pk %}">
        {{room.name}} / ${{room.price}}
    </a>
</h3>
{% endfor %}
<h5>

    {% if page_obj.has_previous %}
    <a href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}

    Page {{page_obj.number}} for {{page_obj.paginator.num_pages}}

    {% if page_obj.has_next %}
    <a href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}





</h5>



{% endblock content %}

templates/rooms/search.html
{% extends 'base.html' %}


{% block page_title %}
Search
{% endblock page_title %}


{% block search-bar %}
{% endblock search-bar %}


{% block content %}
<h2>search</h2>
<form method="get" action="{% url 'rooms:search' %}">
    {{form.as_p}}
    <button>Search</button>
</form>

<h3>Result</h3>
{% for room in rooms %}
{{room.name}}<br>
{% endfor %}


{% if rooms.has_previous %}
<a href="?page={{rooms.previous_page_number}}">Previous</a>
{% endif %}

Page {{rooms.number}} for {{rooms.paginator.num_pages}}

{% if page_obj.has_next %}
<a href="?page={{page_obj.next_page_number}}">Next</a>
{% endif %}


<h4>
{% if rooms.has_previous %}
    <a href="?page={[{rooms.number|add:-1}}">Previous</a>
{% endif %}

Page {{rooms.number}} of {{rooms.paginator.num_pages}}

{% if rooms.has_next %}
    <a href="?page={{rooms.number|add:1}}">Next</a>
{% endif %}
</h4>
{% endblock content %}